### ISSUE TITLE
Migration to swift 3

### ISSUE THREAD

**Issue by farrukhaskari1** [zhangbozhb/ChameleonSwift#1]
Will You be migrating it to swift 3

**Comment by eonist** [comment]
Chaning for loops. And method var arguments mostly!

**Comment by zhangbozhb** [comment]
Will but not now, since Swift 3.0 is preview.  However i start a new branch swift3,  which support Swift3. Thanks for your advice.

**Comment by zhangbozhb** [comment]
default support Swift 3.

pod 'ChameleonSwift', '~> 2.0'
